#!/bin/bash

if [ "$1" == "" ]; then
	echo ""
	echo "You have to specify the environment for which you want to clear the backups"
	echo "These are available:"
	ls -d */
	
	echo ""
else
	cd $1
	./clear ${2}
	cd ..
fi

