#!/bin/bash

# INSTALL .VIMRC
cp ./.vimrc ~/.vimrc

# INSTALL TEMPLATE
if [ ! -d ~/.vim/colors ]
then
    mkdir -p ~/.vim/colors
    echo "New '~/.vim/colors' directory"
fi

TEMPLATE_URL="https://raw.githubusercontent.com/chriskempson/base16-vim"
TEMPLATE_URL+="/master/colors/base16-tomorrow-night.vim"
curl $TEMPLATE_URL > ~/.vim/colors/base16-tomorrow-night.vim

