#!/bin/bash

CWD=$(pwd)
NOW=$(date +%Y%m%d%H%M%S)

echo "======================================================================"
echo "Installing Vim environment"

# BACKUP PREVIOUS CONFIGURATION
if [ -f ~/.vimrc ]; then
	mv ~/.vimrc ~/BACKUP_vimrc_${NOW}
	echo "    Moved previous '.vimrc' to ~/BACKUP_vimrc_${NOW}"
fi
if [ -d ~/.vim ]; then
	mv ~/.vim ~/BACKUP_dotvim_${NOW}
	echo "    Moved previous '.vim/' to ~/BACKUP_dotvim_${NOW}"
fi

# INSTALL .VIMRC
cp ./.vimrc ~/.vimrc
echo "    Installed .vimrc config file"
echo "    ------------------------------------------------------------------"

# Generic function for installing provided files
install_files() {
	echo "    Installing ${1}"
	echo "        Copying..."

	{
		cd ${CWD}
		mkdir -p ${3}
		cp ${2} ${3}

		echo "    Installed ${1}"
	} || {
		echo "    Couldn't install ${1}"
	}

	echo "    ------------------------------------------------------------------"

}

# INSTALL PROVIDED FILES
install_files "Boxy Tomorrow" ./colors/boxy-tomorrow.vim ~/.vim/colors/

# INSTALL PLUG
# for Vim
echo "    Installing Plug"
echo "        Downloading and installing for Vim..."
curl -sfLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo "    Installed Plug for Vim"

# for NeoVim
echo "        Downloading and installing for NeoVim..."
curl -sfLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo "    Installed Plug for NeoVim"
echo "    ------------------------------------------------------------------"


echo "======================================================================"
