#!/bin/bash

echo ""
echo "Installing Vim environment settings..."

# INSTALL .VIMRC
cp ./.vimrc ~/.vimrc
echo "    Installed .vimrc config file"

# INSTALL SNIPPETS
if [ ! -d ~/.vim/snippets ]
then
    mkdir -p ~/.vim/snippets
    echo "    New '~/.vim/snippets' directory"
fi

cp ./snippets/* ~/.vim/snippets/
echo "    Installed Vim snippets"
echo ""

