filetype plugin on
syntax enable

set nocompatible
set path+=**
set wildmenu
set number

" INDENTATION:
set smartindent
set tabstop=4 shiftwidth=4 noexpandtab nosmarttab autoindent
autocmd FileType python setlocal tabstop=4 shiftwidth=4 noexpandtab

" VERTICAL RULERS:
set cc=90
hi ColorColumn ctermbg=Black guibg=Black

" KEY SHORTCUTS:
imap jk <Esc>
imap JK <Esc>
nnoremap <C-d> :sh<CR>

" NETRW Tree View:
let g:netrw_banner=0
let g:netrw_winsize=20
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" SNIPPETS:
imap ,doc """<Esc>o"""<Esc>ka
imap ,class <Esc>:-1read $HOME/.vim/snippets/class_template.py<CR>wce

