#!/bin/bash

echo ""
echo "Pulling latest VSCode environment settings..."

SETTINGS_DIR="${HOME}/Library/Application Support/Code/User"


# INSTALL SETTINGS
cp "${SETTINGS_DIR}/settings.json" ./settings.json
echo "    Pulling settings.json file"

# INSTALL KEYBINDINGS
cp "${SETTINGS_DIR}/keybindings.json" keybindings.json
echo "    Pulling keybindings.json file"
echo ""

